<?php

namespace ContainerRxLM6Sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WTEnTcyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wTEnTcy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wTEnTcy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\BookListController::delete' => ['privates', '.service_locator.KJSb96P', 'get_ServiceLocator_KJSb96PService', true],
            'App\\Controller\\BookListController::edit' => ['privates', '.service_locator.qo8rK6B', 'get_ServiceLocator_Qo8rK6BService', true],
            'App\\Controller\\BookListController::index' => ['privates', '.service_locator.E86grY4', 'get_ServiceLocator_E86grY4Service', true],
            'App\\Controller\\BookListController::new' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BookListController:delete' => ['privates', '.service_locator.KJSb96P', 'get_ServiceLocator_KJSb96PService', true],
            'App\\Controller\\BookListController:edit' => ['privates', '.service_locator.qo8rK6B', 'get_ServiceLocator_Qo8rK6BService', true],
            'App\\Controller\\BookListController:index' => ['privates', '.service_locator.E86grY4', 'get_ServiceLocator_E86grY4Service', true],
            'App\\Controller\\BookListController:new' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BookListController::delete' => '?',
            'App\\Controller\\BookListController::edit' => '?',
            'App\\Controller\\BookListController::index' => '?',
            'App\\Controller\\BookListController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BookListController:delete' => '?',
            'App\\Controller\\BookListController:edit' => '?',
            'App\\Controller\\BookListController:index' => '?',
            'App\\Controller\\BookListController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
