<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'book_index' => [[], ['_controller' => 'App\\Controller\\BookListController::index'], [], [['text', '/']], [], [], []],
    'book_new' => [[], ['_controller' => 'App\\Controller\\BookListController::new'], [], [['text', '/new']], [], [], []],
    'book_edit' => [['id'], ['_controller' => 'App\\Controller\\BookListController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'book_delete' => [['id'], ['_controller' => 'App\\Controller\\BookListController::delete'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'App\Controller\BookListController::index' => [[], ['_controller' => 'App\\Controller\\BookListController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\BookListController::new' => [[], ['_controller' => 'App\\Controller\\BookListController::new'], [], [['text', '/new']], [], [], []],
    'App\Controller\BookListController::edit' => [['id'], ['_controller' => 'App\\Controller\\BookListController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'App\Controller\BookListController::delete' => [['id'], ['_controller' => 'App\\Controller\\BookListController::delete'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
];
